# config/routes/annotations.yaml
controllers:
    resource: '../routes.yaml'
    type: yaml
    prefix:
        pt: '' # don't prefix URLs for Portuguese, the default locale
        en: '/en'
        fr: '/fr'
